### ISSUE TITLE
debian:jessie support removal - upstream debian release policy

### ISSUE THREAD

**Issue by tmc** [nginxinc/docker-nginx#163]
It seems a bit odd to drop jessie support until stretch has actually been released. Is there a stated policy with regard to upstream distro versioning?

**Comment by thresheek** [comment]
My reasoning to upgrade to stretch right now were:

- it's now fully frozen and will not receive breaking changes
- updating to a recent openssl version solves very real problems
- it's also great time because we're doing annual mainline/stable switchover and things are expected to change at that time
- we're actually down in the number of security issues reported by docker vulnerabilty scanner.
