### ISSUE TITLE
why no "fastcgi.conf" file in /etc/nginx?

### ISSUE THREAD

**Issue by bi-kai** [nginxinc/docker-nginx#298]
https://github.com/nginxinc/docker-nginx/blob/baa050df601b5e798431a9db458e16f53b1031f6/mainline/alpine-perl/nginx.vh.default.conf#L35

why there has no "fastcgi.conf" file in /etc/nginx?
I can find it in original nginx-1.15.8.tar.gz, but it's not in nginx docker image.

**Comment by thresheek** [comment]
Use fastcgi_params if you're using debian-based image.

**Comment by davordragic** [comment]
When I compare fastcgi_params and fastcgi.conf in Alpine image, there are differences.
And when using fastcgi_params with nginx.conf from Pimcore 6.9 (https://pimcore.com/docs/pimcore/6.9/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html) I does not work, because of missing
`fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;`

![image](https://user-images.githubusercontent.com/10212089/143851348-016a2125-90aa-444f-8b37-c527b9b6f376.png)

In the end, this is solution to make it work or use alpine image 
![image](https://user-images.githubusercontent.com/10212089/143852025-2f6bd43e-bb5a-4f95-838c-cb2bf42a89a1.png)

I cannot figure out why in clean debian mashine, file is not installed
![image](https://user-images.githubusercontent.com/10212089/143855518-758a1c2e-b57b-4277-a4fa-8fbe514bb317.png)

while on clean centos8 mashine, file comes by default
![image](https://user-images.githubusercontent.com/10212089/143855403-a85b0025-1ff9-4b0e-a03b-31e109ef0ece.png)

Is there any good explanaion?
