### ISSUE TITLE
Use alternative SSL library

### ISSUE THREAD

**Issue by iBobik** [nginxinc/docker-nginx#32]
Some people (inc. me) would like to use other compatible libraries than OpenSSL (e.g. "Amazon s2n":https://github.com/awslabs/s2n) for https. How to configure this package to install things like this?

**Comment by thresheek** [comment]
s2n states that "s2n isn’t intended as a replacement for OpenSSL", so that means it cannot be used with nginx.  Also, seeing that s2n links openssl in when building it, I don't really see the point.

If you wish to add support for different TLS implementation libraries to nginx, please send patches as described in http://nginx.org/en/docs/contributing_changes.html.

Thanks.
