### ISSUE TITLE
Nginx 1.15.10 tag updated again one hour ago instead of 1.15.11?

### ISSUE THREAD

**Issue by siccovansas** [nginxinc/docker-nginx#321]
Nginx 1.15.11 was released yesterday and I see on https://hub.docker.com/_/nginx?tab=tags that updates have been pushed an hour ago. But it seems that 1.15.10 has been updated (again? as this was already available for 2 weeks) while you would expect 1.15.11 to have become available. Maybe I'm jumping the gun or am I correct and was 1.15.10 accidentally updated instead of 1.15.11?

**Comment by thresheek** [comment]
Whatever happens on docker hub is opaque wrt this repo, since the tags can be rebuild without any changes here (e.g. for underlying images receiving security fixes).

Looking at the tags updated, I'm pretty sure it's because of https://github.com/docker-library/official-images/commit/373309d96fc0926b0d45feb7f94f62d653103246.
