### ISSUE TITLE
Upgrade to Alpine 3.10

### ISSUE THREAD

**Issue by claus-strommer-gbl** [nginxinc/docker-nginx#348]
The nginx-stable-alpine image uses a vulnerable version of bzip2 for CVE-2019-12900.  Upgrade to Alpine 3.10 which includes a fixed bzip2 package.

**Comment by thresheek** [comment]
AFAICT, both 3.9 and 3.10 have the same version of bzip2, 1.0.6-r7

https://pkgs.alpinelinux.org/packages?name=bzip2&branch=v3.10
https://pkgs.alpinelinux.org/packages?name=bzip2&branch=v3.9

The curent nginx:alpine and nginx:stable-alpine indeed do ship an outdated version of 1.6.0-r6, so we'd need to rebuild the tag on the docker-library.

Paging @tianon

**Comment by claus-strommer-gbl** [comment]
1.0.6-r7 is the patched version https://git.alpinelinux.org/aports/commit/?h=v3.10.1&id=f47a9e1da5b7f33cf5d46c0541deb454729eee51 .   The package was patched, but the 3.9 image was not updated.

**Comment by yosifkit** [comment]
Images are only rebuilt when they or their parent changes. They also make heavy use of docker build caching.  The last update to the Alpine 3.9 image was https://github.com/docker-library/official-images/pull/5898. So, unless the parent image changes, it would have to be a change in the `RUN` line that installs the bzip package. 

cc @ncopa, what are you thoughts on regenerating the Alpine images more often so that dependent images like nginx get rebuilt?

**Comment by thresheek** [comment]
Closing due to timeout.
