### ISSUE TITLE
docker host nginx.conf doesn't sync with /etc/nginx/nginx.conf in container

### ISSUE THREAD

**Issue by Linshiqi** [nginxinc/docker-nginx#355]
I used -v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf to map host and container , but when I modified nginx.conf in host, it doesn't change in nginx container, or I have to rerun nginx container, it would be nice if I just reload nginx to make new change takes effect.

**Comment by yosifkit** [comment]
You can, but Docker mounts things by inode (not by filename). Your editor (vim, emacs, gedit, ...) writes to a copy and then renames it on top of your original filename to make changes atomic, so the inode that docker and the container are using is then masked from the host.

If you use the folder instead of the singular file it will work as expected  (`-v /etc/nginx/:/etc/nginx/`) and you can send nginx a `HUP` signal to tell it to reload the config (`docker kill -s HUP nginix-container`).
