### ISSUE TITLE
nginx user's home directory belongs to root in alpine image

### ISSUE THREAD

**Issue by gitlawr** [nginxinc/docker-nginx#376]
```
$ docker run -it -u 101 nginx:1.17.4-alpine cat /etc/passwd |grep nginx
nginx:x:101:101:nginx:/var/cache/nginx:/sbin/nologin
$ docker run -it -u 101 nginx:1.17.4-alpine ls -ld /var/cache/nginx
drwxr-xr-x    2 root     root          4096 Oct 21 19:02 /var/cache/nginx
```
As a result I am not able to work under the home directory as the nginx user.

Output from an earlier version:
```
$ docker run -it -u 101 nginx:1.15.8-alpine ls -ld /var/cache/nginx
drwxr-sr-x    2 nginx    nginx         4096 Jan 31  2019 /var/cache/nginx
```

**Comment by westonmyers** [comment]
Offending commit: https://github.com/nginxinc/docker-nginx/commit/b749353968a57ebd9da17e12d23f1a5fb62f9de9

**Comment by thresheek** [comment]
Can you tell me what is your use-case scenario when you want to work as nginx user inside a container?

**Comment by gitlawr** [comment]
I would like to use the non-root user to run Nginx for security reasons.

**Comment by thresheek** [comment]
Right.  The "fast" fix is to redefine the temp paths via configuration to point to e.g. /tmp/proxy_temp etc, just like in https://github.com/nginxinc/docker-nginx-unprivileged

The proper fix would be for this image to support the same, I'm not sure if it will break things when running as root or pose some security problems (cant think of any atm)

**Comment by westonmyers** [comment]
The use case has to do with some nuances with mounted file ownership with kubernetes. Rancher has a shell script that it needs to run before kicking off the nginx daemon.

This script is mounted to `/nginx` with permissions `644` by k8s. This mount is done as root (due to kubernetes), even though we're going to end up running the container/pod as the nginx user. So, as the nginx user, this script is copied to `/var/cache/nginx`. From here, now owned by the nginx user, the script is made executable and then run.

Point of reference: [here](https://github.com/rancher/system-charts/blob/1beff94fceb056ebd6e2a10df2f65ce06c1389df/charts/rancher-monitoring/v0.0.5/charts/prometheus/templates/prometheus.yaml#L20).

It's nice to have a place on the file system that was already owned by the nginx user. I suppose our other option would be to copy to `/tmp/`, set executable, and run from there instead.

**Comment by IoTPlay** [comment]
Also need this solution...

**Comment by thresheek** [comment]
I think /var/cache/nginx while it was used before is not a really good FHS-approved place to store temporary data in.

Please use /tmp or /var/tmp for it.
