### ISSUE TITLE
Add docker healthcheck

### ISSUE THREAD

**Issue by ldrrp** [nginxinc/docker-nginx#392]
I have a different docker image monitoring health status and restarting containers. Can you add a healthcheck to the docker run file so that it may automatically report its status. I tried using wget and curl but the binaries are not on this container.

**Comment by thresheek** [comment]
What kind of health report are we supposed to provide?

**Comment by ldrrp** [comment]
https://docs.docker.com/engine/reference/run/#healthcheck

Probably something that reports that the service is running and has not crashed. for most of my other services i use something like `curl -f http://127.0.0.1/ping` However as i have noted since curl isnt shipped with this container i cant do that here. Normally on a ubuntu install you could also do something like `service nginx status` and as long as it doesnt return something other than 1 for the signal your good to go.

**Comment by thresheek** [comment]
I dont think specifying a predefined health check URI (and a HEALTHCHECK in the image) is a good idea, since this image is very generic and the configuration can be very different for all our upstreams and forcing it upon can lead to a lot of work and suboptimal results.

So far as I can see the real problem is the lack of a tool that will report the user-defined check to an outside system, such as docker compose, or k8s.  As you mentioned, you use curl - maybe we should just ship it as a part of an image, and some documentation on how to utilize health checks if one needs?

**Comment by ldrrp** [comment]
Yes that solution would work. Curl + docs

**Comment by tianon** [comment]
Aren't health checks generally more useful when they're external?

For example, Kubernetes doesn't need anything in the container image to just check a URL or port.

**Comment by ldrrp** [comment]
Well normally on a system install systemd does the checks and can restart the service if it fails but we dont have that here so we need an alternative way. Not sure if that answers your question @tianon ?

**Comment by tianon** [comment]
In this case, the thing that restarts the service is Docker -- if NGINX fails, the container goes away because NGINX is running as PID 1.

**Comment by thresheek** [comment]
Closing this since the consensus seems to be this isnt needed by default.

**Comment by ajostergaard** [comment]
In case of interest to anybody stumbling along... I added following to my docker create:

`--health-cmd='curl -sf https://127.0.0.1/ -o /dev/null || exit 1'`
