### ISSUE TITLE
CVE-2019-20388 vulnerabilities in 1.17.10-alpine docker image

### ISSUE THREAD

**Issue by jayclover** [nginxinc/docker-nginx#403]
HIGH Vulnerability found in os package type (APKG) - libxml2 ( [CVE-2019-20388](https://nvd.nist.gov/vuln/detail/CVE-2019-20388))

Our security system detect listed vulnerabilities in a docker image nginx:1.17.10-alpine.
Could anyone help check and fix it? Thanks.

**Comment by yosifkit** [comment]
I don't think there is a fix available in Alpine: https://gitlab.alpinelinux.org/search?utf8=%E2%9C%93&snippets=&scope=&repository_ref=master&search=CVE-2019-20388&project_id=1.

The same CVE is "vulnerable" in [Debian Jessie, Stretch, and Buster](https://security-tracker.debian.org/tracker/CVE-2019-20388), [RedHat 7 and 8](https://access.redhat.com/security/cve/CVE-2019-20388), and [Ubuntu 12.04 through 20.04](https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-20388.html). So it seems unlikely that there will be a fix anytime soon in most Linux distributions.

It is very common, in order to maintain system and package stability, to not patch a CVE if it is not really a security concern and can be ignored until the next patch release (or bundled with a later major security concern). Debian Security noted it as a "minor issue".

See also https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves.

**Comment by jayclover** [comment]
Hey yosifkit, thanks for your reply. 
Actually this vulnerability didn't exist in latest **alpine:3.11** and **debian:buster-slim**.  The last version **nginx:1.17.9-alpine** is also clean without any vulnerability .

This vulnerability just pop up with the code in dockerfile
&& case "$apkArch" in \
....
esac \

Could you help double check it?

**Comment by yosifkit** [comment]
`nginx:1.17.9-alpine` was based on Alpine 3.10, which has libxml2 version `2.9.9-r3` while `nginx:1.17.10-alpine` is based on Alpine 3.11 which has libxml2 version `2.9.10-r2`.

From the CVE listing, it seems that the vulnerability only affects `2.9.10` (so perhaps the Debian security tracker for CVE-2019-20388 incorrectly states that they are vulnerable :shrug:)

**Comment by thresheek** [comment]
Please use `nginx:1.19.0-alpine`, which has libxml2 `2.9.10-r3` with a fix for that CVE.
