### ISSUE TITLE
[nginx:alpine] CVE-2018-14553

### ISSUE THREAD

**Issue by PaulCharlton** [nginxinc/docker-nginx#434]
upgrading from Alpine:3.11 to Alpine:3.12 will eliminate this CVE

**Comment by thresheek** [comment]
We're waiting for https://gitlab.alpinelinux.org/alpine/abuild/-/issues/9999 to be fixed until we can provide 3.12 packages.

**Comment by PaulCharlton** [comment]
@thresheek -- looks like they closed that one today

**Comment by thresheek** [comment]
Yep - thanks!

It'll take some time to prepare nginx.org infrastructure to produce alpine-3.12 packages, fingers crossed next week we'll have them.

**Comment by tuicci** [comment]
hi @thresheek , any news about promoting from Alpine:3.11 to Alpine:3.12 still this week?

**Comment by thresheek** [comment]
Hello, the packages for 3.12 are now live on nginx.org.

The problem though is that I don't think it's a great idea to re-publish the same tags for a different OS, and the next nginx release is likely to be out in a month or so, so we cant just move to 3.12 soon.

The good news is that this particular CVE, CVE-2018-14553 is now fixed in alpine 3.11, and since we had a rebuild of images not so long ago, both nginx:alpine and nginx:stable-alpine tags now ship libgd with a proper fix.  Marking this closed now.  If you would like to track the move of images to 3.12, please file a new bug and i'll post updates.
