### ISSUE TITLE
log strategy

### ISSUE THREAD

**Issue by scmino** [nginxinc/docker-nginx#44]
Logs are pumped to stdout and stderr, which go to the docker log for the nginx container.
If the container runs a long time this log can be huge, and docker has no way of pruning the log.

What is the general practice for handing of the logs in a docker env?
- One can override error_log and access_log in nginx.conf and put them in another folder, but that has then top be pruned. Or create an image based on nginx and make the log directory a mountable volume.
- or send logs to syslog --log-driver=syslog

(Hmm, a circular mountable access logs of the last XX requests that does not need pruning would be nice ..)

So my question is where there is a consensus about this, or perhaps I missed something obvious?

thanks in advance.

**Comment by yosifkit** [comment]
That looks correct, if you only have one set of logs in you nginx, then `--log-driver=syslog` would probably work best.  Otherwise I would recommend using a custom `nginx.conf` to point logs to a custom location like `/var/log/nginx/{site1,site2}.log` and making that directory a volume and sharing it with `--volumes-from` to a container that processes the logs and it would have to send the sighup to the nginx container to rotate logs.

**Comment by scmino** [comment]
Thx.
Making /var/log/nginx a volume is the easiest in this particular case.
