### ISSUE TITLE
ERR_CONNECTION_REFUSED With Flask App--Gunicorn and NGINX

### ISSUE THREAD

**Issue by Sherry112** [nginxinc/docker-nginx#462]
I am using Flask app, development on VS Code on Ubuntu and was running it on its development server. I wanted to run it on a production server as I wanted to run it on Docker.
To achieve my goal, I used a WSGi standalone container so I followed this tutorial: 
https://medium.com/faun/deploy-flask-app-with-nginx-using-gunicorn-7fda4f50066a
https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04

I completed this tutorial from start to end, without errors. Now when I hit domain name specified in my Nginx/sites-available/app file, it redirects me to the next page, but the next page shows that connection refused.
My error is this:
![Screenshot from 2020-10-21 08-41-54](https://user-images.githubusercontent.com/19520214/96704333-7f297900-1383-11eb-954f-edbe957d0f42.png)

Please help me in this regard. I am in urgent need of help.

**Comment by thresheek** [comment]
Hi @Sherry112,

It looks like a misconfiguration of your application that redirects you to localhost:5000 instead of a proper domain name. I suggest checking with tools like `curl` and not your browser where you can actually see what is going on.  Then, you need to fix the configuration of your app (or pass additional headers on nginx depending on what your app needs) to provide proper redirects.  I believe it's out of scope for nginx docker image, so I'm closing this issue now.
