### ISSUE TITLE
please add httpv3 protocol 

### ISSUE THREAD

**Issue by clcc2019** [nginxinc/docker-nginx#485]
please add httpv3 protocol

**Comment by thresheek** [comment]
Sure, as soon it's available in the released nginx version, it'll be here.

**Comment by DasSkelett** [comment]
Development of HTTP/3 and QUIC support happens in a [separate branch and repository](https://hg.nginx.org/nginx-quic) currently, that's why you can't just "enable" it during compilation.
I'm working on an nginx-quic image for myself, though that will be based on archlinux:base-devel since I can make use of my [AUR package](https://aur.archlinux.org/packages/nginx-quic/) there ^^

**Comment by AlexRMU** [comment]
https://nginx.org/en/docs/http/ngx_http_v3_module.html
The ngx_http_v3_module module (1.25.0) provides experimental support for [HTTP/3](https://datatracker.ietf.org/doc/html/rfc9114).
This module is not built by default, it should be enabled with the [--with-http_v3_module](https://nginx.org/en/docs/configure.html#http_v3_module) configuration parameter.

When do you plan to add this here by default?

**Comment by thresheek** [comment]
Hi @AlexRMU it's available since 1.25.1 in the images.

**Comment by Soberia** [comment]
`--with-stream_quic_module` is also should be enabled.

**Comment by QuAzI** [comment]
Is there any way/env to enable HTTP3 and QUIC by default (with default configuration in container)?

**Comment by thresheek** [comment]
Hi @QuAzI, no, there is no way to do that.
