### ISSUE TITLE
AWS public ECR images not being updated

### ISSUE THREAD

**Issue by trevorrea** [nginxinc/docker-nginx#493]
Hi Folks,

When the AWS public ECR repository launched I changed my environment to use the images hosted there but they don't look to have been updated since it was launched.

Docker Hub has 1.19.6 and the public ECR still only has 1.19.5  Will the images be automatically pushed to both or should I revert to using Docker Hub?

Thanks,
Trevor

**Comment by thresheek** [comment]
Hi @trevorrea!

The new tags are definitely there on AWS ECR (click image tags on the page), but it seems the documentation wasnt updated to reflect that.  Since here on dockerhub the docs are nicely automated, and AWS doesnt really provide a way to do the same there, I guess the best way of action would be to have nice link to docker hub docs for the images.  What do you think?

**Comment by trevorrea** [comment]
Hmm..OK thanks I see that 1.19.6 is actually on the public ECR - doh!  

I was looking at the date pushed and seeing it as "about a month ago" (that's wonderfully imprecise- gee thanks AWS!) and thinking it wasn't being updated as the Docker Hub image was updated 6 days ago on Docker Hub.

Would I be right in assuming that the Docker Hub builds are set to auto-build and deploy and the public ECR ones only for new releases? I don't have an issue moving back to the Docker Hub ones if the public ECR ones are not going to be regularly updated - it would be good to have clarify though.

**Comment by thresheek** [comment]
Indeed, there is no automatic sync between docker hub images (which are built by nice docker library maintainers) and aws ecr so far.  Usually I submit a PR to library, wait until it's merged and then pull & push the images and manifests to ECR so they are in sync.

But, those docker hub tags can be updated without my PRs since docker library rebuilds them every once in a while when there is a bunch of CVEs fixed in underlying images - and there is no way to be notified when such an event occurs, sadly.  So I just check that every week or so and re-pull/push.  I will need to do a cronjob somewhere so this can be automated, but it was a bit low on priority list.

All in all, it's very reasonable to expect that Docker Hub and AWS ECR will be fully synced, and I hope to achieve that soon. Sorry for the troubles.

**Comment by trevorrea** [comment]
OK thanks.  I will close this issue off to reduce noise.

**Comment by thresheek** [comment]
JFYI I've set up a daily cron job, so the sync should be hapenning automatically from now on, albeit with a bit of delay.
