### ISSUE TITLE
what's the difference between bind mount and docker volumes when binding nginx log to host environment?

### ISSUE THREAD

**Issue by cokepizza** [nginxinc/docker-nginx#505]
Hi I have a question when binding nginx log to the host environment, so I create an issue here.

when nginx log is linked in a bind mount method like this,

``` c
volumes:
  - '/var/log/nginx:/var/log/nginx'
```

access.log and error.log are well preserved as expected

**However, it does not work properly when binding nginx logs using a Docker volume**

``` c
volumes:
  - 'nginx-log:/var/log/nginx'
```

access.log and error.log were generated, but no logs were written. (Nginx container and the created docker volume called nginx-log are not written properly)

What is the problem? I want to know the underlying reason. I guess it's the difference between the bind mount and docker volume methods, but what's the exact reason?

**Comment by thresheek** [comment]
Can you provide a better example of what is working and what isnt?

In both variants, logs from inside container are written to `/var/log/nginx/access.log` and `/var/log/nginx/error.log`, and since they are symlinked to /dev/stdout and /dev/stderr accordingly, the data goes into docker log collector and reacheable via e.g. docker logs.  Do you expect something else?  Do you see something else?  Please be more verbose.

**Comment by thresheek** [comment]
Closing due to feedback timeout.
