### ISSUE TITLE
Security Vulnerability  CVE-2021-22831 reported  in the busybox being used

### ISSUE THREAD

**Issue by vegivamp** [nginxinc/docker-nginx#543]
Following Vuln was reported on the version of busybox currently being used.

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28831

**Comment by yosifkit** [comment]
> decompress_gunzip.c in BusyBox through 1.32.1 mishandles the error bit on the huft_build result pointer, with a resultant invalid free or segmentation fault, via malformed gzip data.

Honestly, doesn't seem relevant for an `nginx` container unless you are shelling out busybox's `gunzip`.

---

I assume this is about the Alpine based image since there is no `busybox` in the Debian based image. Unfortunately there is no fix available in Alpine packages (nor does it even look like it is being discussed): https://gitlab.alpinelinux.org/search?utf8=%E2%9C%93&search=CVE-2021-22831.

Once a fix is available the image would need an Alpine image update, since that is where the busybox package is installed.

**Comment by tianon** [comment]
Definitely a false positive in the scanning tool:

- Alpine 3.13: https://git.alpinelinux.org/aports/tree/main/busybox/APKBUILD?h=3.13-stable#n52
- Alpine 3.12: https://git.alpinelinux.org/aports/tree/main/busybox/APKBUILD?h=3.12-stable#n51
- Alpine 3.11: https://git.alpinelinux.org/aports/tree/main/busybox/APKBUILD?h=3.11-stable#n50

**Comment by thresheek** [comment]
Not applicable to current `nginx:alpine` images -> closing.
