### ISSUE TITLE
Support Nginx dind version

### ISSUE THREAD

**Issue by xtreding** [nginxinc/docker-nginx#566]
Please add nginx:dind version. The only change is the parent image of nginx:dind should be [docker:dind image](https://hub.docker.com/layers/docker/library/docker/dind/images/sha256-45667bb65fd02bf020846511c1f59ef9267e2c16439b60509dcf44794307f4f0?context=explore).

dind - docker in docker allows running docker containers inside docker.

**Comment by thresheek** [comment]
Hello @xtreding

What purpose would it serve?

**Comment by xtreding** [comment]
Hi @thresheek! At [Jitsu](https://github.com/jitsucom/jitsu) we use Nginx as a base image and now our service should support running docker containers inside its docker container. docker:dind image is created for solving the problem of running docker containers inside docker container and we need Nginx as well. The easiest way to solve it - to have nginx:dind version.

**Comment by thresheek** [comment]
I think if you're trying to mix and match both `nginx` as a frontend for your images, and `dind`-variant of docker, something is really wrong architecturally in your service. Since `dind` basically requires privileged mode of operation, you're throwing away most of security protection containers offer and making it accessible from outside (that's what `nginx` is for?) seems like a recipe for disaster.

In any case, this case doesnt look like a good fit for a substantial amount users of `nginx` official images which could justify it's addition (at least partially), so no, we will not add and support anything like that.
