### ISSUE TITLE
I can't mount the html directory unless it's source is under either root's or my user's home directory.

### ISSUE THREAD

**Issue by DuncanMarshall** [nginxinc/docker-nginx#595]
I am running the nginx:latest image like so:

```
sudo mkdir /nothome
sudo touch /nothome/worked.txt
sudo docker run -v /nothome:/usr/share/nginx/html:ro --rm --name test-nginx -p 80:80 nginx
```

If I navigate to /worked.txt on that server, I get a 404.  If I exec in to it, the directory is empty.  I've read online that docker requires mounts to be under the users home directory, which isn't true in my experience, but I tried anyway, and it worked:

```
sudo mkdir /home/username/somedir
sudo touch /home/username/somedir/worked.txt
sudo docker run -v /home/username/somedir:/usr/share/nginx/html:ro --rm --name test-nginx -p 80:80 nginx
```

Navigating to /worked.txt returns a 200, and the file contents.  The same happens if I mount to a location under /root on the host.  None of any of the above produces errors.  If I mount to a location other than /usr/share/nginx/html, and then exec in to the nginx container, I can see the contents of that directory.

What's going on here?  And better yet, can I switch it off, so that I can mount to locations which aren't under my/root's home directories?

docker version 20.10.10
Linux kernel 5.4.0-89-generic
Mint 20.2

**Comment by yosifkit** [comment]
There shouldn't be any limitation on bind mount sources for a Linux system. Perhaps it is related to permissions?  The Nginx worker threads that serve content only run as the `nginx` user of the container ([user 101](https://github.com/nginxinc/docker-nginx/blob/328e0f36eae92571465bdd3d268762d2445118f7/stable/debian/Dockerfile#L17)) and so need to be able to access the folder and read any files.

**Comment by henkkasoft** [comment]
I running nginx:1.21.3-alpine with rootless podman to host react app and had a problem that fetching resources (favicon/json files) from server root /usr/share/nginx/html did not work:
`/usr/share/nginx/html/favicon.ico" failed (13: Permission denied)`

@yosifkit many thanks for the tip. When I added nginx user permissions to read and execute files and folders in html folder the problem was solved. Added this line in my Dockerfile to do it:
`RUN chmod -R 755 /usr/share/nginx/html`
