### ISSUE TITLE
Whether openssl is built into the nginx image?

### ISSUE THREAD

**Issue by dawang1024** [nginxinc/docker-nginx#633]
Whether openssl is built into the nginx image?

**Comment by JonasAlfredsson** [comment]
### Debian
```
$ docker run -it nginx:1.21.6 openssl version

OpenSSL 1.1.1k  25 Mar 2021
```
**Answer:** yes

### Alpine
```
$ docker run -it nginx:1.21.6-alpine openssl version

/docker-entrypoint.sh: exec: line 38: openssl: not found
```
```
$ docker run -it nginx:1.21.6-alpine apk list -i | grep ssl

libssl1.1-1.1.1l-r7 x86_64 {openssl} (OpenSSL) [installed]
ssl_client-1.34.1-r3 x86_64 {busybox} (GPL-2.0-only) [installed]
libcrypto1.1-1.1.1l-r7 x86_64 {openssl} (OpenSSL) [installed]
```
**Answer:** no

**Comment by thresheek** [comment]
The openssl binary is not included, however nginx depends on openssl libraries, and those are in.

What is your usecase for having an openssl binary in the image, @dawang1024?

**Comment by thresheek** [comment]
Closing due to feedback timeout.

**Comment by macdjord** [comment]
@thresheek I have a use-case: The [NGINX docs say](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers) to use `openssl ciphers` to find out what ciphers are available. This doesn't work in the Alpine version, because `openssl` proper is not installed, just the libraries. If I had some way of finding out what version of OpenSSL those libraries came from, I could install the same version of OpenSSL elsewhere to run the query.
