### ISSUE TITLE
Use the smaller package envsubst

### ISSUE THREAD

**Issue by ajpaulson** [nginxinc/docker-nginx#651]
In the Dockerfile, gettext is installed, then removed just to get the envsubst binary.
In the APK repos there is an envsubst package with just the 1 binary - could this be considered to neaten up the docker build?

**Comment by thresheek** [comment]
There is no envsubst package in the 3.14 or 3.15 version of Alpine yet.  Maybe if/when it hits a newer release we can take a look at utilizing it instead of doing a gettext hack.  Also, I'm not sure it's 100% compatible with GNU gettext version though and the project repo doesnt inspire much confidence: https://github.com/kaniini/envsubst

And another point is that I would like to keep both debian and alpine images as close as possible, and having different implementations of envsubst might introduce hard to diagnose issues.

**Comment by thresheek** [comment]
Will not implement due to concerns stated above.
