### ISSUE TITLE
Update to version 1.9.12

### ISSUE THREAD

**Issue by sjoerdmulder** [nginxinc/docker-nginx#68]
Was released 24th of Februari

**Comment by binaryanomaly** [comment]
+1

should become part of the release pipeline ;)

**Comment by jrupp** [comment]
+1

I think the complicating factor here is that due to the repo layout change, that there are now lots of different distros being supported.  This may mean coordination with the official docker library for new tags for all of those? Or maybe at least pointing them to a new path to pull the file(s) from.

**Comment by thresheek** [comment]
Indeed it was on hold due to the discussion with library maintainers.

It also is a part of the release pipeline :-)

**Comment by binaryanomaly** [comment]
Awesome, thanks!
