### ISSUE TITLE
Unable to build the lua module with Nginx 

### ISSUE THREAD

**Issue by taysei** [nginxinc/docker-nginx#683]
I keep getting error while using dockerfile in modules folder.

I would like to build nginx with lua only, after using Dockerfile from modules with using command that you given. I still keep getting error. any suggestion?

**docker build --build-arg ENABLED_MODULES="lua" -t my-nginx-with-lua .**

here's log that I got
<img width="1434" alt="Screen Shot 2565-07-18 at 12 40 13" src="https://user-images.githubusercontent.com/55233662/179450976-f2418ced-52da-43b1-a1c8-8f0080594c0c.png">

**Comment by thresheek** [comment]
Hi @taysei !

The lua module as shipped in 1.23.0 tag is broken due to API changes introduced in that release.  We have already pushed the fix to https://hg.nginx.org/pkg-oss/rev/ef1ad3293bbe and the fixed build will be available in 1.23.1.

Meanwhile you can manually point to latest commits in the modules Dockerfile by removing the specific revision from this line: https://github.com/nginxinc/docker-nginx/blob/master/modules/Dockerfile#L29

**Comment by taysei** [comment]
Great! I will wait for release 1.23.1. Thank you
