### ISSUE TITLE
Is the linux s390 image somehow being set as the default?

### ISSUE THREAD

**Issue by rkazak** [nginxinc/docker-nginx#696]
When I run 

```
docker run --name some-nginx -v $(pwd)/some/content:/usr/share/nginx/html:ro -d nginx
```

I seem to be getting the s390 image while I am on am intel laptop...

```
WARNING: The requested image's platform (linux/s390x) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

When I first do a `docker pull nginx` I get the expected platform image downloaded locally...

```
Test2 /Users/rkazak/nginx >docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
7a6db449b51b: Pull complete 
ca1981974b58: Pull complete 
d4019c921e20: Pull complete 
7cb804d746d4: Pull complete 
e7a561826262: Pull complete 
7247f6e5c182: Pull complete 
Digest: sha256:b95a99feebf7797479e0c5eb5ec0bdfa5d9f504bc94da550c2f58e839ea6914f
Status: Downloaded newer image for nginx:latest
docker.io/library/nginx:latest

Test2 /Users/rkazak/nginx >docker run --name mynginx2 -p 81:80 -d nginx
a1f662be792bcd85e2e14459f06dbfcb9c2f38e6b044f7f9383a91d6ef8b2cab
Test2 /Users/rkazak/nginx >
```

Here's what I see under the docker dashboard

<img width="969" alt="Screen Shot 2022-08-25 at 7 11 14 PM" src="https://user-images.githubusercontent.com/3156268/186801673-4726bac9-806e-4724-8a01-52b9a3a70ccb.png">

**Comment by yosifkit** [comment]
It definitely shouldn't be. The image's manifest list did get updated a few times [3-4 days ago](https://github.com/docker-library/repo-info/tree/460bf4f3b2b04ed8c8bca96559254cc177361a9d/repos/nginx/remote) (from the rebuilds caused by the [Debian rebuild](https://github.com/docker-library/official-images/pull/13005)). Each architecture finishes at their own pace and the manifest is updated with new images as they are available; for rebuilds like this, the older architecture-specific images are still referenced in the manifest until the new one is available. So there wasn't a time where `amd64` would have been absent from the manifest.

I'm not sure why your daemon chose to pull the wrong architecture. I assume that you are using Docker Desktop (since it automatically sets up emulation so that any architecture can be run), so the only random explanation that I have is that maybe it is possible that there was a hiccup with Docker Hub that gave a partial manifest? :confused: 

Unable to reproduce:
```console
$ docker run -it --rm --name some-nginx nginx bash
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
7a6db449b51b: Pull complete 
ca1981974b58: Pull complete 
d4019c921e20: Pull complete 
7cb804d746d4: Pull complete 
e7a561826262: Pull complete 
7247f6e5c182: Pull complete 
Digest: sha256:b95a99feebf7797479e0c5eb5ec0bdfa5d9f504bc94da550c2f58e839ea6914f
Status: Downloaded newer image for nginx:latest
root@a56054a582a9:/# dpkg --print-architecture
amd64
root@a56054a582a9:/# 
```

**Comment by thresheek** [comment]
Same here, I'm getting amd64 on Intel hosts, and aarch64 on arm hosts.
