### ISSUE TITLE
Where is the source for headers-more in pkg-oss?

### ISSUE THREAD

**Issue by takumi-ricoh** [nginxinc/docker-nginx#710]
I am not very familiar with Nginx, so let me ask a question here.

I want to add nginx_more functionality to the official nginx docker image, so I did a build with the official DockerFile from the link below. As a result,  I was able to create it successfully by specifying `headers-more` for `ENABLED_MODULES`.
https://github.com/nginxinc/docker-nginx/tree/master/modules

Here is my question. The headers-more specified here seems to be downloaded from `pkg-oss` in the mercual repository, is this the same as the following `headers-more-nginx-module`?

- pkg-oss: https://hg.nginx.org/pkg-oss
- headers:_more: https://www.nginx.com/resources/wiki/modules/headers_more/

I'm not sure, is there a third party module in pks-oss, although the repository is official Nginx?

**Comment by thresheek** [comment]
Hello @takumi-ricoh!

`pkg-oss` indeed has a selection of third party modules build instructions shipped per each nginx open source release.  This is because we ship the exact same selection of modules with our commercial offering, [NGINX Plus](https://www.nginx.com/products/nginx/), and to lower the maintenance burden we decided to open-source parts of our build system, and apply it for nginx as well.

You are correct in your question about whether "headers-more-nginx-module" is the same as "headers-more".

**Comment by takumi-ricoh** [comment]
Hello, thresheek .

I understand very well. Thank you!!!
