### ISSUE TITLE
last commits on alpine. files removed? unexpected end of file ?

### ISSUE THREAD

**Issue by artstylee** [nginxinc/docker-nginx#724]
914af51cd9d1bb37deb6e49ee5070280d9f3f103
4785a604aa40e0b0a69047a61e28781a2b0c2069

looks like we have some issues in these commits?

https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile

**Comment by yosifkit** [comment]
:confused: Where is an "unexpected end of file" error?

Those commits looks similar to what was previewed in https://github.com/docker-library/official-images/pull/13392#issuecomment-1327321249. The images will build upon one another, but aren't yet available to `docker pull` so you'll have to build + tag them in order if you want to build it locally right now:

For example:
```console
$ git clone https://github.com/nginxinc/docker-nginx.git
$ cd docker-nginx/
$ docker build -t nginx:1.22.1-alpine-slim stable/alpine-slim/
...
Successfully tagged nginx:1.22.1-alpine-slim
$ docker build -t nginx:1.22.1-alpine stable/alpine/
...
Successfully tagged nginx:1.22.1-alpine
```

**Comment by artstylee** [comment]
@yosifkit 
im building images by cloning your repo
comparing two folders 
https://github.com/nginxinc/docker-nginx/tree/master/stable/debian
and 
https://github.com/nginxinc/docker-nginx/tree/master/stable/alpine
i see 3 files missed and alpine Dockerfile is being cutted on line 88 ? am i wrong?

**Comment by yosifkit** [comment]
That looks correct to me. `stable/alpine` needs `stable/alpine-slim` to be built first, but `stable/debian` is the base for those since there is no debian-slim.

Stable Alpine:
https://github.com/nginxinc/docker-nginx/blob/4785a604aa40e0b0a69047a61e28781a2b0c2069/stable/alpine/Dockerfile#L6

Stable Debian:
https://github.com/nginxinc/docker-nginx/blob/4785a604aa40e0b0a69047a61e28781a2b0c2069/stable/debian/Dockerfile#L6

And you'll see that the `-perl` variants are `FROM` the plain ones:
https://github.com/nginxinc/docker-nginx/blob/4785a604aa40e0b0a69047a61e28781a2b0c2069/stable/alpine-perl/Dockerfile#L6
https://github.com/nginxinc/docker-nginx/blob/4785a604aa40e0b0a69047a61e28781a2b0c2069/stable/debian-perl/Dockerfile#L6

**Comment by artstylee** [comment]
okay
