### ISSUE TITLE
Why build from source code?

### ISSUE THREAD

**Issue by pyy** [nginxinc/docker-nginx#747]
May I ask why do we build the nginx from source code, not directly use distro's package? Thank you.

**Comment by thresheek** [comment]
Hi @pyy,

We actually use prebuilt packages for the common architectures, however they are not indeed done by an upstream Linux distribution.

The reason we're using self-provided packages is because we can ensure the security updates are done in a timely manner and we wouldnt need to depend on distribution maintainers to take care of that for us.
