### ISSUE TITLE
Update to alpine 3.18

### ISSUE THREAD

**Issue by Earlopain** [nginxinc/docker-nginx#792]
I just wanted to open this to give it a bit more visibility. There have been a few prs made for this already #776 #777 #781 but they got closed since this seems to be blocked currently.

**Comment by thresheek** [comment]
Thanks @Earlopain

For nginx packages as used in those docker images we're using AWS and vendor-provided virtual machine images.  Unfortunately with Alpine 3.18 there is a delay on getting those live on Amazon due to some technical issues they're seeing.

As soon as those issues are sorted out, we'll have 3.18 here too.

**Comment by azizabah** [comment]
@thresheek - Apologies if I'm not following the build and release cycle correctly but the images on [docker hub still appear to be 3.17 based ](https://hub.docker.com/layers/library/nginx/stable-alpine/images/sha256-fc9b8c25953467e406a95ab7b65cbfa9f56b6f24cffcd5ba07b30c2d388490b6?context=explore)

Is there an ETA on when those will be updated to 3.18? We are specifically looking at that stable-alpine tag.

**Comment by thresheek** [comment]
Hi @azizabah !

There is no ETA - the move will happen when a new release of 1.24.x branch is out.  It is unknown yet when this will happen.
