### ISSUE TITLE
Inconsistencies in available archs for 1.25.4 alpine images

### ISSUE THREAD

**Issue by buchdag** [nginxinc/docker-nginx#866]
### Describe the bug

The architectures available on Docker Hub for the 1.25.4 alpine images are inconsistent between supposedly similar tags.

![Screenshot 2024-02-15 at 09 15 02](https://github.com/nginxinc/docker-nginx/assets/13685826/a675b24f-4f9c-4e0b-a729-ed203cfdb3df)
![Screenshot 2024-02-15 at 09 15 09](https://github.com/nginxinc/docker-nginx/assets/13685826/13ac5ee1-2c2b-4db6-aa51-318cc1e3e279)
![Screenshot 2024-02-15 at 09 15 47](https://github.com/nginxinc/docker-nginx/assets/13685826/58832f80-67ce-4d78-9b46-9c0ee7b43da8)
![Screenshot 2024-02-15 at 09 22 12](https://github.com/nginxinc/docker-nginx/assets/13685826/33537a4f-b434-460d-8b86-8106bb67a327)

### To reproduce

1. Attempt to pull `nginx:1.25.4-alpine` for `arm/v7` arch.

### Expected behavior

Available arch should be identical for similar tags, as previously.

**Comment by thresheek** [comment]
Hi @buchdag, thanks for letting us know.

@tianon @yosifkit -- is there something we can do to get the manifests fixed?

Thanks!

**Comment by yosifkit** [comment]
In order to prevent architectures from disappearing from already published tags, we build the image index from the most recent available for each architecture. So, on a tag like `nginx:1.25-alpine`, it contains items from all arches currently tagged as `1.25-alpine` (can be seen in like `amd64/nginx:1.25-alpine` or `arm32v7/nginx:1.25-alpine`) and can consequently have Nginx `1.25.3` and `1.25.4` images while those other arches continue building the new version. The `1.25.4*` tags are more specific/new and so don't have an older version that can be used for those architectures.

Which is to say, those architectures are still in progress and the more generic tags have images that contain the older version. Once everything is built, both sets of tags will have the full set of architectures.

For example, you can see the differing Nginx versions in the image index for `nginx:1.25-alpine` (see the `org.opencontainers.image.version` fields):
https://explore.ggcr.dev/?image=nginx:1.25-alpine@sha256:cedce0b6e276efe62bbf15345053f44cdc5d1c834a63ab7619aa8355093f85d2&mt=application%2Fvnd.oci.image.index.v1%2Bjson&size=8483

**Comment by buchdag** [comment]
@yosifkit makes total sense, thanks for the info 👍 

As @thresheek I'd be curious to know if there is a way to monitor progress other than browsing and refreshing the registry explorer, but I consider this closed.

**Comment by yosifkit** [comment]
Our new builds happen via Jenkins (https://doi-janky.infosiftr.net/job/wip/job/new/) with some architectures building on GitHub Actions, but it's a bit complicated right now to find a specific image's build. Each of the `trigger-[arch]` jobs has a queue of ready-to-build images it is working through; the `build-[arch]` jobs are an active build of a particular image.
