### ISSUE TITLE
Using configuration for stdout/stderr redirection

### ISSUE THREAD

**Issue by wernight** [nginxinc/docker-nginx#87]
Nginx should support redirecting errors and outputs to stdout and stderr directly in the [config](https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/nginx.conf) which should be cleaner than the current hack in https://github.com/nginxinc/docker-nginx/blob/master/mainline/alpine/Dockerfile:

	# forward request and error logs to docker log collector
	&& ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

If there is a good reason, it'd be useful for other people to update the comment so as to reflect the reason.

Related bug: https://github.com/iler/alpine-nginx-pagespeed/issues/4#issuecomment-215092184

**Comment by thresheek** [comment]
It was done this way because It's easier to make symlinks than to change configuration file(s).  If you wish, you can set it directly in your configuration files.

**Comment by thresheek** [comment]
Anyway, nginx will always try to open /var/log/nginx/error.log (well actually it's what's provided on configure-time on --error-log-path), even if error_log is set to something else in the main context.  This is done because errors might arise when parsing the configuration and nginx cant use log sinks defined in the configuration.

Hope that clarifies why symlinking is a better idea.

**Comment by wernight** [comment]
Changing the configuration is easy (I just linked to it) but I agree the that if users submit their own and its invalid then Docker wouldn't show the error. This is a good reason.

**Comment by kaihendry** [comment]
RE https://github.com/nginxinc/docker-nginx/issues/87#issuecomment-215377991 how does one reset the file to just {access,error}.log without the symlink? Delete it and touch the file?

**Comment by wernight** [comment]
Delete and restart nginx.
