### ISSUE TITLE
Rebuild image regularly

### ISSUE THREAD

**Issue by edermi** [nginxinc/docker-nginx#88]
Hi,

since it's OpenSSL patch time again, I'd like to suggest to rebuild the nginx image regularly even if there are no new releases, just to keep dependencies up to date. This can afaik be done automatically on Docker Hub and improves security of many users.

**Comment by psftw** [comment]
Issues with OpenSSL are typically addressed at the base operating system level, and then downstream images are updated accordingly (whether or not the base image update was security-related).  I believe the specific OpenSSL issue you are referring to is being tracked https://github.com/docker-library/official-images/issues/1691

**Comment by edermi** [comment]
At least for Alpine, there's already a fix in the repos for about 25 hours:
http://git.alpinelinux.org/cgit/aports/commit/?id=cbb0770d837b43f77e1ae29c7d60f29b8e71e87a

As far as I can see, openssl is installed by the nginx Dockerfile, so I guess a nginx image rebuild installs the latest OpenSSL version?

**Comment by thresheek** [comment]
@edermi correct.

**Comment by edermi** [comment]
@thresheek So, I suppose it's a rather good idea to build images automatically every few days in order to keep up with security updates provided by alpine's repositories. Is there anything speaking against regular rebuilds?

**Comment by leedm777** [comment]
:+1: to periodic builds.

In an ideal world filled with unicorns and rainbows, you would only build when an update is available upstream (on either Debian or Alpine). And even more ideal would be the ability to know what's been fixed in a given tag.

**Comment by psftw** [comment]
In cases like this where the base OS image contains the software that was updated, I would prefer to update the base image first.  Yes, technically the nginx image could be rebuilt with a newer openssl within the time lag it takes to get the base image updated, but doing this would require a Dockerfile change to break the cache (or perhaps a special one-off request to build with --no-cache).  Neither case is worth the extra headaches IMHO because if the time lag for base image updates is far behind upstream then we are fundamentally broken to begin with.  I'm definitely +1 on thinking about how to shorten the gap between upstream and Docker images as well as documenting the changes to tags caused by rebuilds -- a "tag audit" if you like.  I'm not sure what the Official Repo team uses to stay on top of image updates based on critical CVEs, but they have done a good enough job in my opinion every time I've looked in to it.  It may be worth an issue to investigate what's done today and how it could be improved.

Docker's Security Scanning solution doesn't show historical results for a given tag, and the only way to reference deprecated versions of tags is via hashes to manifests that may (?) get garbage collected one day.  It would be an interesting experiment to look through the history of https://github.com/docker-library/docs/blob/master/nginx/tag-details.md to get that information, or better yet set up something to track it for a given set of images so that you could capture the historical versions and audit them as they are created.

**Comment by franhp** [comment]
A full month has passed and *stable* nginx image is still vulnerable to `CVE-2016-2107`. 
What would be required to trigger a new release/build that is at least not vulnerable?

https://github.com/docker-library/official-images/issues/1691 suggests that both Alpine and Debian base images are now ready.

**Comment by thresheek** [comment]
What makes you think that the current stable images are vulnerable to CVE-2016-2107?

**Comment by franhp** [comment]
@thresheek My apologies, I've just learnt something about Debian I didn't know

Saw the output of `openssl version` as `OpenSSL 1.0.1k 8 Jan 2015` and thought it was vulnerable as it is smaller than `1.0.1t`. 
Turns out that Debian reuses the version number (or rather doesn't bother changing it) on their security patches so you need to use the version number on the output of `dpkg` instead. The stable image for nginx uses now version `1.0.1k-3+deb8u5`, which https://security-tracker.debian.org/tracker/CVE-2016-2107 shows as fixed and thus nginx containers are not vulnerable

Now I've got a server using `1.0.1k-3+deb8u2` that I need to update ...

**Comment by thresheek** [comment]
To sump up: the image maintainer has no means to procure a new image build other than bumping the image version (so, essentially, a new release); this is handled by docker-library maintainers in case of CVE.  If you feel like there is an urgent need to do so, file a bug under https://github.com/docker-library/official-images/labels/cve-tracker.

**Comment by andreif** [comment]
@thresheek Are you always sure that base `alpine:3.4` image is always updated in case there were CVE in it? Is this why you don't need `apk update && apk upgrade` in Nginx Dockerfile?
